param(
  [Parameter(Mandatory=$true)][string]$RepoRoot
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
function Read-Source([string]$Relative){$path=Join-Path $RepoRoot $Relative;if(-not(Test-Path -LiteralPath $path)){throw "REGRESSION=FAIL missing=$Relative"};Get-Content -LiteralPath $path -Raw}
function Require-Contains([string]$Text,[string]$Needle,[string]$Name){if(-not $Text.Contains($Needle)){throw "REGRESSION=FAIL check=$Name expected=contains"};Write-Host "REGRESSION_CHECK=PASS name=$Name"}
function Require-NotContains([string]$Text,[string]$Needle,[string]$Name){if($Text.Contains($Needle)){throw "REGRESSION=FAIL check=$Name expected=absent"};Write-Host "REGRESSION_CHECK=PASS name=$Name"}
$game=Read-Source 'src\game\states\GameState.as'
$offline=Read-Source 'src\game\utils\OfflineSave.as'
$world=Read-Source 'src\game\gui\popups\WorldMapWindow.as'
$matchup=Read-Source 'src\game\gui\pvp\PvPMatchUpDialog.as'
$combat=Read-Source 'src\game\gui\pvp\PvPCombatSetupDialog.as'
$match=Read-Source 'src\game\net\PvPMatch.as'
$tile=Read-Source 'src\game\battlefield\TileMapGraphic.as'
$scene=Read-Source 'src\game\isometric\IsometricScene.as'
$saveDialog=Read-Source 'src\game\gui\GiveFilePermissionDialog.as'
$pvpHud=Read-Source 'src\game\gui\pvp\PvPHUD.as'
$pvpBooster=Read-Source 'src\game\gui\pvp\PvPBoosterBar.as'
$character=Read-Source 'src\game\isometric\characters\IsometricCharacter.as'
$animation=Read-Source 'src\game\characters\AnimationController.as'
$mapData=Read-Source 'src\game\battlefield\MapData.as'
$desertTile=Read-Source 'src\config\tile_map_desert.csv'
$baseConfig=Read-Source 'src\config\army_config_base.json'
$utils=Read-Source 'src\Utils.as'
$resourceManager=Read-Source 'src\com\dchoc\graphics\DCResourceManager.as'
$loot=Read-Source 'src\game\gameElements\LootReward.as'
$pvpAttack=Read-Source 'src\game\actions\PvPAttackEnemyAction.as'
$pvpInstall=Read-Source 'src\game\actions\PvPAttackEnemyInstallationAction.as'
$pvpFire=Read-Source 'src\game\actions\PvPFireMissionAction.as'
$gameHud=Read-Source 'src\game\gui\GameHUD.as'
$perfOverlay=Read-Source 'android\native\diagnostics\java\com\valverde\armyattack\diagnostics\PerformanceOverlay.java'
$swfPatch=Read-Source 'Tools\CI\Patch-AndroidPerformanceSwf.ps1'
$pvpDebrief=Read-Source 'src\game\gui\pvp\PvPDebriefingDialog.as'
$pvpEnemy=Read-Source 'src\game\characters\PvPEnemyUnit.as'
$diagMarker=Read-Source 'android\native\diagnostics\as3\com\valverde\armyattack\diagnostics\DiagnosticsMarker.as'
$diagExtension=Read-Source 'android\native\diagnostics\java\com\valverde\armyattack\diagnostics\DiagnosticsExtension.java'
Require-Contains $game 'private var mPvPReturnMapId: String = "Home";' 'pvp_return_map_state'
Require-Contains $game 'if (param3) {' 'pvp_transient_switch_guard'
Require-Contains $game 'this.mPvPMatch.mOpponent = null;' 'pvp_end_resets_opponent'
Require-Contains $offline 'savedMap["map_data"]["map_id"] = map_id;' 'saved_map_id_normalization'
Require-NotContains $world 'switchOfflineArea' 'worldmap_no_parallel_switch_implementation'
Require-Contains $matchup 'private static const PANEL_COUNT:int = 3;' 'pvp_owns_three_visible_slots'
Require-NotContains $matchup 'GameState.mInstance.endPvP();' 'matchup_close_does_not_end_unstarted_match'
Require-Contains $combat 'chance.toString() + "%"' 'pvp_chance_is_percentage'
Require-NotContains $combat '_loc1_ - _loc2_' 'pvp_raw_float_difference_removed'
Require-NotContains $combat 'mScene.mFog.destroy();' 'pvp_dialog_does_not_destroy_scene_fog'
Require-Contains $match 'while(_loc2_ < 24 && this.mOpponentUnits.length < 4)' 'pvp_randomization_bounded'
Require-Contains $match 'private function consumeFailedEnemyAction() : void' 'pvp_ai_no_action_has_bounded_progress'
Require-Contains $match 'catch(error:Error)' 'pvp_ai_exception_is_contained'
Require-Contains $match '[PVP_AI_NO_ACTION]' 'pvp_ai_no_action_is_instrumented'
Require-Contains $tile 'this.disposeCachedTileBitmaps();' 'native_bitmap_cache_disposed_before_rebuild'
Require-Contains $scene 'Math.abs(this.mContainer.scaleX - param1) < 0.0001' 'zoom_noop_avoids_reraster'
Require-NotContains $game 'this.mHUD.openGiveFilePermissionScreen();' 'mobile_obsolete_v22_save_gate_removed'
Require-Contains $game 'defaultSettings["savelocation"] = this.mSaveLocation;' 'mobile_internal_save_default_persisted'
Require-Contains $saveDialog 'private function fitToScreen():void' 'mobile_save_dialog_has_viewport_fit'
Require-Contains $saveDialog 'stageHeight * 0.92 / mClip.height' 'mobile_save_dialog_height_bounded'
Require-Contains $saveDialog 'var done:Function = mDoneCallback;' 'mobile_save_choice_closes_immediately'
Require-NotContains $saveDialog 'this.buttonSavePressed(param1); // twice' 'mobile_save_duplicate_permission_requests_removed'
Require-Contains $game 'private function waitForMapTilemap(param1: String, param2: Function, param3: Function): void' 'map_switch_waits_for_tilemap'
Require-Contains $game 'this.mPendingOfflineSwitchMapId = param1;' 'desert_switch_deferred_until_resources_ready'
Require-Contains $game 'this.mPendingPvPMapId = _loc1_;' 'pvp_switch_deferred_until_resources_ready'
Require-Contains $game 'private var mLoadingActive: Boolean = false;' 'loading_lifecycle_state_guard'
Require-Contains $game 'if (this.mLoadingActive) {' 'stale_loading_callback_blocked'
Require-Contains $game '_loc1_.removeEventListener(_loc2_, this.LoadingFinished);' 'stop_loading_detaches_async_callback'
Require-Contains $scene 'if (!popup.isClosed()) {' 'worldmap_popup_forced_closed_before_scene_swap'
Require-Contains $scene 'GameState.mInstance.mCurrentMapId.indexOf("pvp_") == 0' 'pvp_prestate_map_bypasses_campaign_cloud_cover'
Require-Contains $pvpHud 'this.mGame.mPvPMatch.mOpponent' 'pvp_hud_uses_selected_opponent'
Require-NotContains $pvpHud 'getOpponent("1")' 'pvp_hud_hardcoded_opponent_removed'
Require-Contains $character '_loc6_.gotoAndStop(1);' 'unit_power_badge_single_icon'
Require-NotContains $character '_loc6_.gotoAndStop(this.getPower())' 'unit_power_badge_cumulative_frames_removed'
Require-Contains $utils '!_loc4_.isLoaded(_loc6_) && !_loc4_.isAddedToLoadingList(_loc6_)' 'swf_resource_requests_deduplicated'
Require-Contains $resourceManager 'this.loadTextFile("../config/dummy.json",param2);' 'offline_swf_uses_embedded_symbol_shim'
Require-Contains $resourceManager 'return getDefinitionByName(_loc3_) as Class;' 'offline_swf_class_lookup_is_embedded'
Require-Contains $game 'ZoomLevelsMobile ? this.mMapData.mMapSetupData.ZoomLevelsMobile : this.mMapData.mMapSetupData.ZoomLevels' 'mobile_zoom_falls_back_for_legacy_maps'
Require-Contains $game 'private function areMapResourcesReady(param1: String): Boolean' 'map_transition_waits_for_all_resources'
Require-Contains $game 'swf/desert_backgroud_01' 'desert_transition_swf_required'
Require-Contains $game 'recoverOfflineTransition' 'map_transition_has_rollback'
Require-Contains $game 'this.initMap(null, this.mCurrentMapId);' 'pvp_scene_initializes_explicitly'
Require-Contains $mapData 'private static function parseTileMapCsv' 'tilemap_csv_is_normalized'
Require-Contains $mapData 'TILEMAP_CELL_COUNT expected=' 'tilemap_dimension_mismatch_fails_fast'
Require-Contains $mapData 'TILEMAP_ROW_WIDTH row=' 'tilemap_rows_validated_independently'
Require-Contains $mapData 'param1.indexOf("pvp_") == 0' 'pvp_tile_ownership_not_state_order_dependent'
$desertRows=@($desertTile -split "\r?\n" | Where-Object { $_.Trim().Length -gt 0 })
if($desertRows.Count -ne 73){throw "REGRESSION=FAIL check=desert_tilemap_rows expected=73 actual=$($desertRows.Count)"}
for($i=0;$i -lt $desertRows.Count;$i++){
  $cells=@($desertRows[$i].Split(',') | Where-Object { $_.Trim().Length -gt 0 })
  $expectedWidth=if($i -eq 29 -or $i -eq 30){72}else{71}
  if($cells.Count -ne $expectedWidth){throw "REGRESSION=FAIL check=desert_tilemap_width row=$($i+1) expected=$expectedWidth actual=$($cells.Count)"}
  if($expectedWidth -eq 72 -and $cells[71].Trim() -ne '99'){throw "REGRESSION=FAIL check=desert_legacy_padding row=$($i+1) expected=99 actual=$($cells[71])"}
}
Write-Host 'REGRESSION_CHECK=PASS name=desert_tilemap_legacy_padding_71x73_plus2'
Require-Contains $mapData 'legacy_desert_flat_padding' 'desert_legacy_flattening_preserves_authored_alignment'
Require-Contains $mapData 'TILEMAP_LEGACY_PADDING expected=2' 'desert_legacy_padding_fails_fast_if_partial'
Require-Contains $animation 'notifyOwnerAnimationReady' 'animation_materialization_refreshes_owner'
Require-Contains $character 'public function refreshStatusHints(): void' 'unit_status_placeholders_refreshed_immediately'
Require-Contains $world 'private function requestClose(): void' 'worldmap_close_is_idempotent'
Require-NotContains $world '_loc2_.removeEventListener(MouseEvent.MOUSE_DOWN, this.mouseDown);' 'worldmap_cancel_wrong_listener_removal_removed'
Require-Contains $combat 'USE_BUTTON_STATES_ANIM = false' 'pvp_setup_buttons_have_deterministic_frames'
Require-Contains $pvpBooster 'Utils.removeAllChildren(_loc3_);' 'pvp_booster_placeholders_cleared'
Require-Contains $baseConfig '"ZoomLevelsMobile": "40, 75, 100"' 'pvp_mobile_zoom_explicit_in_config'
Require-Contains $baseConfig '"swf/desert_backgroud_01"' 'desert_secondary_swf_declared_in_config'
Require-Contains $scene 'private static const TOOLTIP_TIMEOUT_MS: int = 1000;' 'tooltip_timer_fixed_wall_clock_timeout'
Require-Contains $scene 'new Timer(TOOLTIP_TIMEOUT_MS, 1)' 'tooltip_timer_one_shot'
Require-Contains $scene 'TimerEvent.TIMER_COMPLETE, this.appearTimerComplete' 'tooltip_timer_uses_completion_event'
Require-Contains $scene 'private function stopToolTipTimer(): void' 'tooltip_timer_has_idempotent_cleanup'
Require-NotContains $scene 'mAppearDelayMs' 'tooltip_timer_no_frame_rate_derived_delay'
Require-NotContains $scene 'appearTimerTick' 'tooltip_timer_no_repeating_tick_handler'
Require-Contains $offline 'savedata["active_map_id"] = map_id.indexOf("pvp_") == -1 ? map_id : "Home";' 'offline_save_persists_only_stable_world'
Require-Contains $offline 'savedata["saveversion"] = 7;' 'offline_save_version_bumped_for_active_map'
Require-Contains $offline 'if (version < 6) {' 'offline_old_save_active_map_migration'
Require-Contains $offline 'if (version < 7) savedata["offline_pvp_booster_seed_cleanup_pending"] = true;' 'offline_old_save_booster_cleanup_migration'
Require-Contains $offline 'var activeMapId: String = "Home";' 'offline_restore_defaults_home'
Require-Contains $offline 'GameState.GRAPHICS_MAP_ID_LIST.indexOf(activeMapId) < 0' 'offline_restore_rejects_unknown_map'
Require-Contains $offline 'restore_active_map_after_home_bootstrap' 'offline_restore_waits_for_home_bootstrap'
Require-Contains $offline 'if (activeMapId != "Home" && mMaps[activeMapId]) {' 'offline_restore_requires_saved_destination'
Require-Contains $offline 'GameState.mInstance.executeSwitchMap(activeMapId, null);' 'offline_restore_uses_resource_gated_transition'
Require-Contains $offline '[OFFLINE_RESTORE_MAP]' 'offline_restore_is_instrumented'
Require-NotContains $offline 'loadMap(mMaps[activeMapId]);' 'offline_restore_never_direct_loads_cold_desert'
Require-Contains $match 'public function checkTerminalState() : Boolean' 'pvp_terminal_check_is_explicit'
Require-Contains $match 'getPvPEnemyAliveUnits().length' 'pvp_victory_counts_only_alive_enemies'
Require-Contains $match '[PVP_TERMINAL]' 'pvp_terminal_transition_is_instrumented'
Require-Contains $game 'this.mPvPMatch.checkTerminalState()' 'pvp_terminal_check_not_blocked_by_action_queue'
Require-Contains $game 'this.resetActions();' 'pvp_debrief_clears_stale_actions'
Require-Contains $pvpHud 'popup_pvp_loot' 'pvp_offline_debrief_uses_embedded_symbol'
Require-Contains $pvpHud '[PVP_DEBRIEF_OPEN]' 'pvp_debrief_open_is_instrumented'
Require-Contains $offline 'public static function ensureOfflinePvPBoosters(): void' 'offline_pvp_booster_starter_is_idempotent'
Require-NotContains $offline 'inventory.addItems(booster, 3);' 'offline_pvp_boosters_are_not_auto_seeded'
Require-Contains $offline 'inventory.addItems(boosters[index], -3);' 'offline_pvp_legacy_seed_is_removed'
Require-Contains $pvpBooster 'if(_loc3_ != null && _loc5_ > 0)' 'pvp_booster_bar_uses_positive_real_inventory_only'
Require-Contains $pvpBooster 'private function setPanelQuantity' 'pvp_booster_quantity_renderer_exists'
Require-Contains $pvpBooster 'mBoosterQuantityFields' 'pvp_booster_quantity_fields_cached'
Require-Contains $pvpBooster 'DCResourceManager.getInstance().isLoaded(_loc3_)' 'pvp_booster_waits_for_real_icon'
Require-Contains $pvpBooster 'var _loc2_:int = this.mCursorPos;' 'pvp_booster_slots_start_at_cursor'
Require-NotContains $pvpBooster 'this.mCursorPos - Math.max(0,PANEL_COUNT - this.mBoosterInventory.length / 2)' 'pvp_booster_right_alignment_bug_removed'
Require-Contains $match 'public function activateBooster(param1:BoosterItem) : Boolean' 'pvp_booster_activation_has_runtime_effect'
Require-Contains $match 'public function getActiveRangeBoost() : int' 'pvp_range_booster_runtime_value'
Require-Contains $match 'public function getBoostedDamage' 'pvp_damage_booster_runtime_value'
Require-Contains $match 'public function consumeActionBooster' 'pvp_action_booster_consumption'
Require-Contains $match 'this.mGame.mPlayerProfile.mInventory.addItems(booster,-1);' 'pvp_booster_inventory_consumed'
Require-Contains $match 'param1 is CollectibleItem' 'pvp_debrief_tracks_only_collectibles'
Require-Contains $character 'public function getMaxHealth(): int' 'pvp_health_booster_has_safe_cap'
Require-Contains $pvpBooster 'mPvPMatch.activateBooster(booster)' 'pvp_booster_bar_calls_runtime_activation'
Require-NotContains $pvpBooster 'mPvPMatch.mActivatedBooster = this.mBoosterInventory' 'pvp_booster_dead_assignment_removed'
Require-Contains $pvpAttack 'getBoostedDamage(baseDamage,actorCount)' 'pvp_unit_attack_applies_damage_booster'
Require-Contains $pvpAttack 'consumeActionBooster("enemy_unit_attack")' 'pvp_unit_attack_consumes_booster'
Require-Contains $pvpInstall 'consumeActionBooster("enemy_installation_attack")' 'pvp_installation_attack_consumes_booster'
Require-Contains $pvpInstall 'mPvPMatch.addIngameCollectible(_loc12_)' 'pvp_installation_drop_tracked'
Require-Contains $pvpFire 'mPvPMatch.addIngameCollectible(_loc10_)' 'pvp_firemission_drop_tracked'
Require-Contains $pvpFire 'import game.actions.FireMissionAction;' 'pvp_firemission_import_is_ffdec_compilable'
Require-Contains $loot '[PVP_LOOT_DEFER_UI]' 'pvp_loot_suppresses_campaign_collection_popup'
Require-Contains $game 'public function getEffectivePlayerAttackRange' 'pvp_range_booster_affects_target_selection'
Require-Contains $game '[MAP_SWITCH_BEGIN]' 'worldmap_transition_begin_instrumented'
Require-Contains $game '[MAP_SWITCH_COMMIT]' 'worldmap_transition_commit_instrumented'
Require-Contains $game '[MAP_INPUT_RESTORED]' 'worldmap_input_restore_instrumented'
Require-Contains $game 'music_commit=deferred' 'desert_music_not_used_as_false_transition_signal'
Require-Contains $gameHud '[WORLD_MAP_OPEN] mode=embedded' 'offline_world_map_bypasses_fake_swf_loader'
Require-Contains $gameHud 'var scaleFactor:Number = Math.min(scaleFactorWidth, scaleFactorHeight);' 'mobile_hud_scale_factor_ffdec_semicolon'
Require-Contains $swfPatch '(?://.*)?\z' 'ffdec_config_preprocessor_accepts_trailing_comments'
Require-Contains $offline '[OFFLINE_SWITCH_MAP_BEGIN]' 'offline_map_loader_begin_instrumented'
Require-Contains $offline '[OFFLINE_SWITCH_MAP_END]' 'offline_map_loader_end_instrumented'
Require-Contains $perfOverlay 'captureProcessDiagnostics(dir);' 'performance_zip_captures_process_state'
Require-Contains $perfOverlay 'logcat-own-process.txt' 'performance_zip_includes_own_process_logcat'
Require-Contains $perfOverlay 'threads.txt' 'performance_zip_includes_thread_dump'
Require-Contains $perfOverlay 'smaps-rollup.txt' 'performance_zip_includes_memory_rollup'
Require-Contains $swfPatch "Class='game.gameElements.LootReward'" 'swf_patch_includes_pvp_loot_class'
Require-Contains $swfPatch "Class='game.actions.PvPAttackEnemyAction'" 'swf_patch_includes_pvp_attack_class'
Require-Contains $swfPatch "Class='game.gui.GameHUD'" 'swf_patch_includes_gamehud_class'
Require-Contains $pvpDebrief 'GameState.mInstance.endPvP(GameState.mInstance.openPvPMatchUpDialog);' 'pvp_play_again_exits_old_match_before_ranking'
Require-NotContains $pvpDebrief 'GameState.mInstance.getHud().openPvPMatchUpDialog();' 'pvp_play_again_no_longer_opens_ranking_over_dead_battle'
Require-Contains $game 'public function endPvP(param1: Function = null): void' 'pvp_end_supports_deferred_replay'
Require-Contains $game 'this.mPendingOfflineSwitchCompletion = param4;' 'map_switch_owns_completion_callback'
Require-Contains $game 'public function requestWorldMapSwitch(param1:String): void' 'worldmap_switch_owned_by_gamestate'
Require-Contains $game 'public function restoreGameplayInputAfterPopup(): void' 'popup_close_has_explicit_input_restore'
Require-Contains $world 'game.requestWorldMapSwitch(param1);' 'worldmap_dispatches_before_released_instance_can_stall'
Require-NotContains $world 'setTimeout(this.executePendingSwitch' 'worldmap_released_popup_timer_removed'
Require-NotContains $world 'mPendingSwitchMapId' 'worldmap_popup_no_longer_owns_transition_state'
Require-Contains $offline 'GameState.mInstance.initObjects(null);' 'first_time_offline_map_runs_object_lifecycle'
Require-Contains $game 'MAP_MUSIC_COMMIT' 'desert_music_occurs_after_core_map_commit'
Require-Contains $diagMarker 'nativeContext.call("logEvent"' 'swf_native_diagnostics_bridge'
Require-Contains $diagExtension 'functions.put("logEvent", new LogEventFunction());' 'ane_exposes_log_event'
Require-Contains $perfOverlay 'game-events.jsonl' 'performance_zip_contains_game_events'
Require-Contains $perfOverlay 'game-events-summary.json' 'performance_zip_summarizes_game_events'
Require-Contains $perfOverlay 'lag-snapshots' 'performance_lag_marker_captures_immediate_snapshot'
Require-Contains $perfOverlay 'proc-sched.txt' 'performance_zip_captures_process_scheduler_state'
Require-Contains $perfOverlay 'LIVE_RENDER_RECORDING_MS = 5000L' 'profiler_live_text_throttled'
Require-Contains $resourceManager 'SWF_RESOURCE_STATS' 'swf_resource_lookup_stats_instrumented'
Require-Contains $resourceManager 'SWF_ALIAS_RISK' 'swf_alias_risk_instrumented'
Require-Contains $resourceManager 'SWF_CLASS_MISS' 'swf_class_miss_instrumented'
Require-Contains $animation 'ANIMATION_STATS' 'animation_churn_stats_instrumented'
Require-Contains $swfPatch "Class='com.dchoc.graphics.DCResourceManager'" 'swf_patch_includes_resource_manager_diagnostics'
Require-Contains $utils 'DiagEvent("UI_BUTTON"' 'central_button_events_instrumented'
Require-Contains $pvpEnemy '"opfor_move_dark"' 'pvp_enemy_movement_preserves_visual_identity'
Require-Contains $pvpEnemy 'resolveOpforGraphics' 'pvp_enemy_generic_symbols_remapped_to_opfor'
Require-Contains $pvpEnemy 'this.mResolvedGraphicsArray = this.resolveOpforGraphics(param3.mGraphicsArray);' 'pvp_enemy_resolved_graphics_are_loaded'
Require-Contains $pvpEnemy 'initAnimations(this.mResolvedGraphicsArray);' 'pvp_enemy_animation_controller_uses_opfor_graphics'
Require-NotContains $pvpEnemy 'initAnimations(param3.mGraphicsArray);' 'pvp_enemy_original_graphics_bypass_removed'
Require-Contains $pvpEnemy 'pvp_premium_infantry_' 'pvp_enemy_sniper_has_dark_fallback'
Require-Contains $pvpEnemy '_loc7_ = _loc6_[_loc8_] as PlayerUnit;' 'pvp_enemy_ai_assigns_candidate_before_range_check'
Require-Contains $pvpEnemy '(_loc9_ = _loc7_.getCell()) != null' 'pvp_enemy_ai_guards_candidate_cell'
Require-Contains $swfPatch "Class='game.characters.PvPEnemyUnit'" 'swf_patch_includes_pvp_enemy_visual'
Require-Contains $swfPatch "Class='game.gui.pvp.PvPDebriefingDialog'" 'swf_patch_includes_pvp_debriefing'
$audit=Join-Path $RepoRoot 'Tools\CI\Audit-SwfCore.ps1'
if(-not(Test-Path -LiteralPath $audit)){throw "REGRESSION=FAIL missing=Tools/CI/Audit-SwfCore.ps1"}
& $audit -RepoRoot $RepoRoot
Write-Host 'REGRESSION_CHECK=PASS name=swf_core_audit_reproducible'
Write-Host 'REGRESSION=PASS suite=android-runtime-v3.17-opfor-desert-alignment-swf-telemetry'
